In [1]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder , StandardScaler

df = pd.read_csv('IPL_Matches_tail_300.csv')
df.head()

   Unnamed: 0.1  ...  winner_encoded
0             0  ...               8
1             1  ...               5
2             2  ...               7
3             3  ...               2
4             4  ...               9

[5 rows x 28 columns]

In [2]:
X = df[['team1_runs' , 'toss_decision' , 'team1_wickets' , 'win_by_wickets']]
X.head()

   team1_runs toss_decision  team1_wickets  win_by_wickets
0       150.0           bat              6               5
1       159.0         field              7               5
2       157.0           bat              8               5
3       188.0         field              6               7
4       207.0         field              4               0

In [3]:
from sklearn.pipeline import Pipeline

transformers = [
    ('num' , SimpleImputer(strategy='mean') , ['team1_runs']),
    ('scale' , StandardScaler() , ['team1_wickets']),
    ('cat' , Pipeline([ ('imputer' , SimpleImputer(strategy = 'most_frequent')) , ('encoder' , OneHotEncoder() ) ]) , ['toss_decision']) ,
    ('details' , 'passthrough' , ['win_by_wickets']),
]

In [6]:
preprocessor = ColumnTransformer(transformers, remainder='passthrough')
X_transformed = preprocessor.fit_transform(X)

print(type(X_transformed))
X_transformed = pd.DataFrame(X_transformed , columns = ['team1_runs' , 'team1_wickets' , 'toss_decision_bat' , 'toss_decision_field' , 'win_by_wickets'] , )

X_transformed.head(10)

<class 'numpy.ndarray'>

   team1_runs  team1_wickets  ...  toss_decision_field  win_by_wickets
0       150.0      -0.131775  ...                  0.0             5.0
1       159.0       0.333313  ...                  1.0             5.0
2       157.0       0.798402  ...                  0.0             5.0
3       188.0      -0.131775  ...                  1.0             7.0
4       207.0      -1.061952  ...                  1.0             0.0
5       157.0       0.798402  ...                  1.0             7.0
6       130.0       1.263490  ...                  0.0             7.0
7       178.0       0.333313  ...                  1.0             5.0
8       193.0      -0.131775  ...                  1.0             0.0
9       191.0      -0.596863  ...                  1.0             0.0

[10 rows x 5 columns]