In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv('IPL_Matches_tail_300.csv')
df.head()

,Unnamed: 0.1,Unnamed: 0,date,season,city,venue,team1,team2,toss_winner,toss_decision,...,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players,winner_encoded
0,0,0,20-05-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Chennai Super Kings,Rajasthan Royals,Chennai Super Kings,bat,...,R Ashwin,M Nayyar,CB Gaffaney,NA Patwardhan,YC Barde,PG Pathak,20,"RD Gaikwad, DP Conway, MM Ali, N Jagadeesan, A...","YBK Jaiswal, JC Buttler, SV Samson, D Padikkal...",8
1,1,1,21-05-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Delhi Capitals,Mumbai Indians,Mumbai Indians,field,...,JJ Bumrah,J Srinath,Nitin Menon,Tapan Sharma,HAS Khalid,GR Sadashiv Iyer,20,"PP Shaw, DA Warner, MR Marsh, RR Pant, SN Khan...","Ishan Kishan, RG Sharma, D Brevis, Tilak Varma...",5
2,2,2,22-05-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,Punjab Kings,Sunrisers Hyderabad,bat,...,Harpreet Brar,J Srinath,AK Chaudhary,NA Patwardhan,CB Gaffaney,Navdeep Singh,20,"PK Garg, Abhishek Sharma, RA Tripathi, AK Mark...","JM Bairstow, S Dhawan, M Shahrukh Khan, MA Aga...",7
3,3,3,24-05-2022,2022,Kolkata,"Eden Gardens, Kolkata",Rajasthan Royals,Gujarat Titans,Gujarat Titans,field,...,DA Miller,M Nayyar,BNJ Oxenford,VK Sharma,MA Gough,J Madanagopal,20,"YBK Jaiswal, JC Buttler, SV Samson, D Padikkal...","WP Saha, Shubman Gill, MS Wade, HH Pandya, DA ...",2
4,4,4,25-05-2022,2022,Kolkata,"Eden Gardens, Kolkata",Royal Challengers Bengaluru,Lucknow Super Giants,Lucknow Super Giants,field,...,RM Patidar,M Nayyar,J Madanagopal,MA Gough,BNJ Oxenford,VK Sharma,20,"V Kohli, F du Plessis, RM Patidar, GJ Maxwell,...","Q de Kock, KL Rahul, M Vohra, DJ Hooda, MP Sto...",9

In [4]:
df['match_date'] = pd.to_datetime(
    df['date']
)

df.head()

/tmp/ipykernel_8861/83071948.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['match_date'] = pd.to_datetime(

,Unnamed: 0.1,Unnamed: 0,date,season,city,venue,team1,team2,toss_winner,toss_decision,...,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players,winner_encoded,match_date
0,0,0,20-05-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Chennai Super Kings,Rajasthan Royals,Chennai Super Kings,bat,...,M Nayyar,CB Gaffaney,NA Patwardhan,YC Barde,PG Pathak,20,"RD Gaikwad, DP Conway, MM Ali, N Jagadeesan, A...","YBK Jaiswal, JC Buttler, SV Samson, D Padikkal...",8,2022-05-20
1,1,1,21-05-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Delhi Capitals,Mumbai Indians,Mumbai Indians,field,...,J Srinath,Nitin Menon,Tapan Sharma,HAS Khalid,GR Sadashiv Iyer,20,"PP Shaw, DA Warner, MR Marsh, RR Pant, SN Khan...","Ishan Kishan, RG Sharma, D Brevis, Tilak Varma...",5,2022-05-21
2,2,2,22-05-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,Punjab Kings,Sunrisers Hyderabad,bat,...,J Srinath,AK Chaudhary,NA Patwardhan,CB Gaffaney,Navdeep Singh,20,"PK Garg, Abhishek Sharma, RA Tripathi, AK Mark...","JM Bairstow, S Dhawan, M Shahrukh Khan, MA Aga...",7,2022-05-22
3,3,3,24-05-2022,2022,Kolkata,"Eden Gardens, Kolkata",Rajasthan Royals,Gujarat Titans,Gujarat Titans,field,...,M Nayyar,BNJ Oxenford,VK Sharma,MA Gough,J Madanagopal,20,"YBK Jaiswal, JC Buttler, SV Samson, D Padikkal...","WP Saha, Shubman Gill, MS Wade, HH Pandya, DA ...",2,2022-05-24
4,4,4,25-05-2022,2022,Kolkata,"Eden Gardens, Kolkata",Royal Challengers Bengaluru,Lucknow Super Giants,Lucknow Super Giants,field,...,M Nayyar,J Madanagopal,MA Gough,BNJ Oxenford,VK Sharma,20,"V Kohli, F du Plessis, RM Patidar, GJ Maxwell,...","Q de Kock, KL Rahul, M Vohra, DJ Hooda, MP Sto...",9,2022-05-25

In [8]:
df['match_date'].dt.year.unique()

array([2022, 2023, 2024, 2025, 2026], dtype=int32)

In [7]:
df['match_date'].dt.month.unique()

array([5, 3, 4, 6], dtype=int32)

In [12]:
df['match_date'].dt.day_name()

0         Friday
1       Saturday
2         Sunday
3        Tuesday
4      Wednesday
         ...
295       Sunday
296      Tuesday
297    Wednesday
298       Friday
299       Sunday
Name: match_date, Length: 300, dtype: object

In [13]:
df['match_date'].dt.day_name().value_counts()

match_date
Sunday       72
Saturday     52
Friday       38
Tuesday      38
Wednesday    36
Monday       32
Thursday     32
Name: count, dtype: int64

In [15]:
df['is_weekend'] = np.where(
    df['match_date'].dt.day_name().isin(['Saturday' , 'Sunday']),
    1,
    0
)

df[['team1' , 'team2' , 'match_date' , 'is_weekend']]

,team1,team2,match_date,is_weekend
0,Chennai Super Kings,Rajasthan Royals,2022-05-20,0
1,Delhi Capitals,Mumbai Indians,2022-05-21,1
2,Sunrisers Hyderabad,Punjab Kings,2022-05-22,1
3,Rajasthan Royals,Gujarat Titans,2022-05-24,0
4,Royal Challengers Bengaluru,Lucknow Super Giants,2022-05-25,0
...,...,...,...,...
295,Delhi Capitals,Kolkata Knight Riders,2026-05-24,1
296,Royal Challengers Bengaluru,Gujarat Titans,2026-05-26,0
297,Rajasthan Royals,Sunrisers Hyderabad,2026-05-27,0
298,Rajasthan Royals,Gujarat Titans,2026-05-29,0
299,Gujarat Titans,Royal Challengers Bengaluru,2026-05-31,1