In [1]:
import pandas as pd

df = pd.read_csv('IPL_Matches_tail_300.csv')

df.head()

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players
0,20-05-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Chennai Super Kings,Rajasthan Royals,Chennai Super Kings,bat,150.0,6,...,5,R Ashwin,M Nayyar,CB Gaffaney,NA Patwardhan,YC Barde,PG Pathak,20,"RD Gaikwad, DP Conway, MM Ali, N Jagadeesan, A...","YBK Jaiswal, JC Buttler, SV Samson, D Padikkal..."
1,21-05-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Delhi Capitals,Mumbai Indians,Mumbai Indians,field,159.0,7,...,5,JJ Bumrah,J Srinath,Nitin Menon,Tapan Sharma,HAS Khalid,GR Sadashiv Iyer,20,"PP Shaw, DA Warner, MR Marsh, RR Pant, SN Khan...","Ishan Kishan, RG Sharma, D Brevis, Tilak Varma..."
2,22-05-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,Punjab Kings,Sunrisers Hyderabad,bat,157.0,8,...,5,Harpreet Brar,J Srinath,AK Chaudhary,NA Patwardhan,CB Gaffaney,Navdeep Singh,20,"PK Garg, Abhishek Sharma, RA Tripathi, AK Mark...","JM Bairstow, S Dhawan, M Shahrukh Khan, MA Aga..."
3,24-05-2022,2022,Kolkata,"Eden Gardens, Kolkata",Rajasthan Royals,Gujarat Titans,Gujarat Titans,field,188.0,6,...,7,DA Miller,M Nayyar,BNJ Oxenford,VK Sharma,MA Gough,J Madanagopal,20,"YBK Jaiswal, JC Buttler, SV Samson, D Padikkal...","WP Saha, Shubman Gill, MS Wade, HH Pandya, DA ..."
4,25-05-2022,2022,Kolkata,"Eden Gardens, Kolkata",Royal Challengers Bangalore,Lucknow Super Giants,Lucknow Super Giants,field,207.0,4,...,0,RM Patidar,M Nayyar,J Madanagopal,MA Gough,BNJ Oxenford,VK Sharma,20,"V Kohli, F du Plessis, RM Patidar, GJ Maxwell,...","Q de Kock, KL Rahul, M Vohra, DJ Hooda, MP Sto..."

In [4]:
df.columns

Index(['date', 'season', 'city', 'venue', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'team1_runs', 'team1_wickets', 'team2_runs',
       'team2_wickets', 'winner', 'result_type', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'match_referee', 'umpire1',
       'umpire2', 'tv_umpire', 'reserve_umpire', 'overs_limit',
       'team1_players', 'team2_players'],
      dtype='object')

In [5]:
num_cols = df.select_dtypes(include = 'number').columns

num_cols

Index(['season', 'team1_runs', 'team1_wickets', 'team2_runs', 'team2_wickets',
       'win_by_runs', 'win_by_wickets', 'overs_limit'],
      dtype='object')

In [13]:
mean_values = df[num_cols].mean()
print(mean_values)

season            2024.446667
team1_runs         188.136519
team1_wickets        6.283333
team2_runs         171.761092
team2_wickets        5.823333
win_by_runs         15.370000
win_by_wickets       3.110000
overs_limit         20.000000
dtype: float64

In [14]:
median_values = df[num_cols].median()
print(median_values)

season            2024.0
team1_runs         191.0
team1_wickets        6.0
team2_runs         175.0
team2_wickets        6.0
win_by_runs          0.0
win_by_wickets       3.0
overs_limit         20.0
dtype: float64

In [15]:
mode_values = df[num_cols].mode()
print(mode_values)

   season  team1_runs  team1_wickets  team2_runs  team2_wickets  win_by_runs  \
0    2023       159.0            5.0       199.0           10.0          0.0
1    2025       162.0            6.0         NaN            NaN          NaN
2    2026       214.0            NaN         NaN            NaN          NaN

   win_by_wickets  overs_limit
0             0.0         20.0
1             NaN          NaN
2             NaN          NaN

In [21]:
std_values = df[num_cols].std()
print(std_values)

season             1.174060
team1_runs        37.459500
team1_wickets      2.153722
team2_runs        40.548182
team2_wickets      2.753919
win_by_runs       25.368978
win_by_wickets     3.249579
overs_limit        0.000000
dtype: float64

In [20]:
df['team1_runs'].value_counts()

team1_runs
159.0    7
162.0    7
214.0    7
203.0    6
199.0    6
        ..
264.0    1
75.0     1
225.0    1
247.0    1
255.0    1
Name: count, Length: 128, dtype: int64

In [22]:
df.describe()

,season,team1_runs,team1_wickets,team2_runs,team2_wickets,win_by_runs,win_by_wickets,overs_limit
count,300.000000,293.000000,300.000000,293.000000,300.000000,300.000000,300.000000,300.0
mean,2024.446667,188.136519,6.283333,171.761092,5.823333,15.370000,3.110000,20.0
std,1.174060,37.459500,2.153722,40.548182,2.753919,25.368978,3.249579,0.0
min,2022.000000,25.000000,1.000000,0.000000,0.000000,0.000000,0.000000,20.0
25%,2023.000000,163.000000,5.000000,152.000000,4.000000,0.000000,0.000000,20.0
50%,2024.000000,191.000000,6.000000,175.000000,6.000000,0.000000,3.000000,20.0
75%,2025.000000,212.000000,8.000000,200.000000,8.000000,23.000000,6.000000,20.0
max,2026.000000,287.000000,10.000000,265.000000,10.000000,112.000000,10.000000,20.0

# mean imputation

we use mean values for missing data

In [23]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [29]:
df = pd.read_csv('IPL_Matches_tail_300.csv')
print(df.shape)

df.info()

(300, 25)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             300 non-null    object
 1   season           300 non-null    int64
 2   city             300 non-null    object
 3   venue            300 non-null    object
 4   team1            300 non-null    object
 5   team2            300 non-null    object
 6   toss_winner      300 non-null    object
 7   toss_decision    300 non-null    object
 8   team1_runs       293 non-null    float64
 9   team1_wickets    300 non-null    int64
 10  team2_runs       293 non-null    float64
 11  team2_wickets    300 non-null    int64
 12  winner           288 non-null    object
 13  result_type      300 non-null    object
 14  win_by_runs      300 non-null    int64
 15  win_by_wickets   300 non-null    int64
 16  player_of_match  290 non-null    object
 17  match_referee    300 non-null    object
 18  umpire1          300 non-null    object
 19  umpire2          300 non-null    object
 20  tv_umpire        300 non-null    object
 21  reserve_umpire   300 non-null    object
 22  overs_limit      300 non-null    int64
 23  team1_players    300 non-null    object
 24  team2_players    300 non-null    object
dtypes: float64(2), int64(6), object(17)
memory usage: 58.7+ KB

In [30]:
df.isnull().sum()

date                0
season              0
city                0
venue               0
team1               0
team2               0
toss_winner         0
toss_decision       0
team1_runs          7
team1_wickets       0
team2_runs          7
team2_wickets       0
winner             12
result_type         0
win_by_runs         0
win_by_wickets      0
player_of_match    10
match_referee       0
umpire1             0
umpire2             0
tv_umpire           0
reserve_umpire      0
overs_limit         0
team1_players       0
team2_players       0
dtype: int64

In [40]:
mean_df = df.copy()
mean_value = mean_df['team1_runs'].mean()

print(mean_value)
mean_df['team1_runs'].isnull().sum()

188.13651877133105

np.int64(7)

In [41]:
mean_df['team1_runs'] = mean_df['team1_runs'].fillna(mean_value)
mean_df['team1_runs'].isnull().sum()

np.int64(0)

# Median Imputation

In [42]:
median_df = df.copy()
median_value = median_df['team2_runs'].median()

print(median_value)

median_df['team2_runs'].isnull().sum()

175.0

np.int64(7)

In [43]:
median_df['team2_runs'] = median_df['team2_runs'].fillna(median_value)
median_df['team2_runs'].isnull().sum()

np.int64(0)

# using scikit learn

In [57]:
mean_imp = SimpleImputer(strategy='mean')
median_imp = SimpleImputer(strategy='median')
mode_imp = SimpleImputer(strategy = 'most_frequent')

df['team1_runs'] = mean_imp.fit_transform(df[['team1_runs']])
df['team2_runs'] = median_imp.fit_transform(df[['team2_runs']])
df['player_of_match'] = mode_imp.fit_transform(df[['player_of_match']])[: , 0]

df.isnull().sum()

date                0
season              0
city                0
venue               0
team1               0
team2               0
toss_winner         0
toss_decision       0
team1_runs          0
team1_wickets       0
team2_runs          0
team2_wickets       0
winner             12
result_type         0
win_by_runs         0
win_by_wickets      0
player_of_match     0
match_referee       0
umpire1             0
umpire2             0
tv_umpire           0
reserve_umpire      0
overs_limit         0
team1_players       0
team2_players       0
dtype: int64

but what about winners , i mean we can use mode , but the results wont be that accurate , we have to use mode but with some tweaks

In [59]:
winner_counts = df['winner'].value_counts()

null_indices = df[df['winner'].isnull()].index
print(null_indices)

Index([38, 52, 103, 168, 183, 195, 206, 209, 233, 237, 262, 299], dtype='int64')

In [63]:
for idx in null_indices :
  team1 = df.loc[idx , 'team1']
  team2 = df.loc[idx , 'team2']

  team1_wins = winner_counts.get(team1 , 0)
  team2_wins = winner_counts.get(team2 , 0)

  if team1_wins >= team2_wins :
    df.loc[idx , 'winner'] = team1
  else :
    df.loc[idx , 'winner'] = team2

df['winner'].isnull().sum()

In [65]:
print("Rows where 'winner' was imputed:")
display(df.loc[null_indices, ['team1', 'team2', 'winner']])

Rows where 'winner' was imputed:

                     team1                        team2                 winner
38     Chennai Super Kings        Kolkata Knight Riders  Kolkata Knight Riders
52    Lucknow Super Giants          Chennai Super Kings    Chennai Super Kings
103    Sunrisers Hyderabad                 Punjab Kings           Punjab Kings
168       Rajasthan Royals                 Punjab Kings       Rajasthan Royals
183         Delhi Capitals             Rajasthan Royals       Rajasthan Royals
195           Punjab Kings        Kolkata Knight Riders           Punjab Kings
206         Delhi Capitals          Sunrisers Hyderabad    Sunrisers Hyderabad
209           Punjab Kings               Delhi Capitals           Punjab Kings
233       Rajasthan Royals               Gujarat Titans         Gujarat Titans
237  Kolkata Knight Riders                 Punjab Kings           Punjab Kings
262  Kolkata Knight Riders         Lucknow Super Giants  Kolkata Knight Riders
299         Gujarat Titans  Royal Challengers Bengaluru         Gujarat Titans