In [4]:
import pandas as pd

df = pd.read_csv('IPLPlayerStat.csv')
df.head()

,Unnamed: 0,player,runs,boundaries,balls_faced,wickets,balls_bowled,runs_conceded,matches,batting_avg,batting_strike_rate,boundaries_percent,bowling_economy,bowling_avg,bowling_strike_rate,catches,stumpings
0,0,A Ashish Reddy,280,31,196,NaN,270,400,28,10.00,142.86,15.82,8.89,22.22,15.00,8,0
1,1,A Badoni,161,18,139,2.0,12,12,11,14.64,115.83,12.95,6.00,6.00,6.00,8,0
2,2,A Chandila,4,0,7,11.0,234,245,12,0.33,57.14,0.00,6.28,22.27,21.27,2,0
3,3,A Chopra,53,7,75,0.0,0,0,6,8.83,70.67,9.33,0.00,0.00,0.00,2,0
4,4,A Choudhary,25,2,20,5.0,108,144,5,5.00,125.00,10.00,8.00,28.80,21.60,0,0

In [5]:
def player_form(avg):
  if avg <= 10 :
    return "Poor"
  elif avg <= 15 :
    return "Average"
  elif avg <= 20 :
    return "Good"
  elif avg <= 25 :
    return "Excellent"
  else :
    return "Outstanding"

df['player_form'] = df['batting_avg'].apply(player_form)

df[['player' , 'batting_avg' , 'player_form']].head()

           player  batting_avg player_form
0  A Ashish Reddy        10.00        Poor
1        A Badoni        14.64     Average
2      A Chandila         0.33        Poor
3        A Chopra         8.83        Poor
4     A Choudhary         5.00        Poor

In [6]:
df['player_form'].unique()

array(['Poor', 'Average', 'Excellent', 'Good', 'Outstanding'],
      dtype=object)

In [10]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(
    categories=[['Poor' , 'Average' , 'Good' , 'Excellent' , 'Outstanding']]
)

df['player_form_encoded'] = encoder.fit_transform(df[['player_form']]).astype(int)
df[['player_form' , 'player_form_encoded']].head(10)

  player_form  player_form_encoded
0        Poor                    0
1     Average                    1
2        Poor                    0
3        Poor                    0
4        Poor                    0
5        Poor                    0
6   Excellent                    3
7        Poor                    0
8        Good                    2
9        Poor                    0

In [12]:
df[['player' , 'batting_avg' , 'player_form' , 'player_form_encoded']].head(10)

           player  batting_avg player_form  player_form_encoded
0  A Ashish Reddy        10.00        Poor                    0
1        A Badoni        14.64     Average                    1
2      A Chandila         0.33        Poor                    0
3        A Chopra         8.83        Poor                    0
4     A Choudhary         5.00        Poor                    0
5     A Dananjaya         4.00        Poor                    0
6      A Flintoff        20.67   Excellent                    3
7        A Kumble         0.83        Poor                    0
8       A Manohar        15.43        Good                    2
9        A Mishra         2.35        Poor                    0

In [13]:
df.to_csv("IPLPlayerStat.csv")